### ISSUE TITLE
Decompiler doesn't provide output with no error

### ISSUE THREAD

**Issue by civiltox** [ChloeDoesThings/ChloeRT#1]

**Comment by ChloeDoesThings** [comment]
> All I can really provide is what happens and how to reproduce. Simply just open the exe and attach this file: [dhframework.txt](https://github.com/ChloeDoesThings/ChloeRT/files/14895952/dhframework.txt) (This is a localscript from a game called Da Hood, maybe 4-5k lines? I also tried with a different framework which is 3k lines, and it decompiled just fine). Change to decompile mode and click decompile. It'll just remove the decompilation output text and then never show an output. I'm not too familiar with C#, C++, or decompilation/reversing, so I can't be sure whether I'm doing something wrong.

The decompiler is very buggy atm, I'm working on implementing a less buggy one (based off of unluau v2). When it releases it should fix the issue.

My discord username is "te1amon" if you wanna add me.

**Comment by ChloeDoesThings** [comment]
I'll keep this open where I can keep note of it

**Comment by civiltox** [comment]
> > All I can really provide is what happens and how to reproduce. Simply just open the exe and attach this file: [dhframework.txt](https://github.com/ChloeDoesThings/ChloeRT/files/14895952/dhframework.txt) (This is a localscript from a game called Da Hood, maybe 4-5k lines? I also tried with a different framework which is 3k lines, and it decompiled just fine). Change to decompile mode and click decompile. It'll just remove the decompilation output text and then never show an output. I'm not too familiar with C#, C++, or decompilation/reversing, so I can't be sure whether I'm doing something wrong.
> 
> The decompiler is very buggy atm, I'm working on implementing a less buggy one (based off of unluau v2). When it releases it should fix the issue.
> 
> My discord username is "te1amon" if you wanna add me.

Alright, that sounds good. I never really figured out how to make unluau v2 work, even with your fork. I added you on Discord by the way
